export const residentHeaderCells = [
  {
    id: 'residentId',
    numeric: true,
    disablePadding: true,
    label: 'Resident ID',
    index: 1,
  },
  {
    id: 'firstName',
    numeric: false,
    disablePadding: false,
    label: 'First Name',
    index: 2,
  },
  {
    id: 'lastName',
    numeric: false,
    disablePadding: false,
    label: 'Last Name',
    index: 3,
  },
  {
    id: 'roomNumber',
    numeric: false,
    disablePadding: false,
    label: 'Room Number',
    index: 4,
  },
  {
    id: 'assistedSupervisor',
    numeric: false,
    disablePadding: false,
    label: 'Supervisor',
    index: 5,
  },
  {
    id: 'contactNumber',
    numeric: false,
    disablePadding: false,
    label: 'Contact Number',
    index: 6,
  },
  {
    id: 'createdAt',
    numeric: false,
    disablePadding: false,
    label: 'Created Date',
    index: 7,
  },
  {
    id: 'updatedAt',
    numeric: false,
    disablePadding: false,
    label: 'Updated Date',
    index: 8,
  },
];

export const employeeHeaderCells = [
  {
    id: 'employeeId',
    numeric: true,
    disablePadding: true,
    label: 'Employee ID',
    index: 1,
  },
  {
    id: 'firstName',
    numeric: false,
    disablePadding: false,
    label: 'First Name',
    index: 2,
  },
  {
    id: 'lastName',
    numeric: false,
    disablePadding: false,
    label: 'Last Name',
    index: 3,
  },
  {
    id: 'contactNumber',
    numeric: false,
    disablePadding: false,
    label: 'Contact Number',
    index: 4,
  },
  {
    id: 'createdAt',
    numeric: false,
    disablePadding: false,
    label: 'Created Date',
    index: 5,
  },
  {
    id: 'updatedAt',
    numeric: false,
    disablePadding: false,
    label: 'Updated Date',
    index: 6,
  },
];